### ISSUE TITLE
Products.MimetypesRegistry used in p.a.blob.utils but no dependency

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.blob#19]
Products.MimetypesRegistry is imported in ``utils.py``, but there is no dependency in setup.py. 
This breaks tests in other modules (i.e. plone.subrequest) depending on this package and expecting correctly given dependencies.

**Comment by jensens** [comment]
look at plone/plone.subrequest@f92904947f358fd12f095b0eb0ca5d27b187afc8 for such a workaround

**Comment by tisto** [comment]
@jensens Why don't we just declare this dependency in plone.app.blob setup.py?

**Comment by jensens** [comment]
thats the plan, will do, and as soon theres a new release i remove it from plone.subrequest. but i want to have it working now and tests green.
